apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: rcc-manager

images:
- name: williambr2022/rcc-londrina-front
  newName: williambr2022/rcc-londrina-front
  newTag: 3fa0a387a965364f275e4d59905a8cdad950fdff
